[package]
name = "bar-wlrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.11.2"
log = "0.4.20"
smithay-client-toolkit = "0.18.1"
wayland-client = { version = "0.31.2", features = ["log"] }
